service: hasher

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
#  stage: production

functions:
  hasher:
    handler: handler.hasher
    events:
      - http:
          path: urls/{image}
          method: get

plugins:
  - serverless-webpack
